### PR TITLE
fixed postcss deprecated functions (eachAtRule & eachDecl)

### PR DESCRIPTION
**Pull request by rajdee**
This commit corrects some of the functions that are deprecated since version 5.xx

### CODE REVIEW

**Comment by TrySound** [comment]
@rajdee Tests should be passed

**Comment by rajdee** [comment]
All tests have passed

**Comment by TrySound** [comment]
@rajdee You added polyfill to devDeps. PostCSS do not support promises now. Just add polyfill in tests instead of plugin code.

**Comment by rajdee** [comment]
I added polyfill in the plugin because you support node 0.10 which doesn't support promises.

**Comment by TrySound** [comment]
@rajdee We let users add polyfill, but we don't add this. Tests should be passed with polyfill in tests to prevent using another feature from new versions. But usually we just remove 0.10 from tests.
https://github.com/jonathantneal/oldie/blob/master/.travis.yml

**Comment by rajdee** [comment]
It sounds great, because without support of node v0.10, tests pass without polyfill

**Comment by TrySound** [comment]
@rajdee You can drop it.

**Comment by jonathantneal** [comment]
Very good. @TrySound, anything you’d like me to wait on before I merge this?

**Comment by TrySound** [comment]
@jonathantneal Let's merge

**Pull request merged**
